"""initial migration

Revision ID: 932843dad5ab
Revises: 
Create Date: 2025-08-01 14:11:39.223426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932843dad5ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('cellar_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wine', sa.String(), nullable=False),
    sa.Column('grape', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('vintage', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('tasting_notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_cellar_records_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cellar_records')
    op.drop_table('users')
    # ### end Alembic commands ###
